services:
  - type: web
    name: dashboard-economico
    runtime: python
    rootDir: ./app1
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: segundo-dashboard
    runtime: python
    rootDir: ./app2
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0